### ISSUE TITLE
ci: init

### ISSUE THREAD

**Issue by oSumAtrIX** [KevinX8/Negate#1]
Add basic CI/CD in order to test, lint and build releases automatically. Combine it with Gitflow in order to allow stable branches and releases.

**Comment by KevinX8** [comment]
closed by https://github.com/KevinX8/Negate/commit/60119cb9d37c251427e3b418118363ae15811766 and https://github.com/KevinX8/Negate/commit/09e57b97a9beebc7a9ace65fcbfb0c8b29e8dce6

**Comment by oSumAtrIX** [comment]
Does CI trigger on refactoring?

**Comment by KevinX8** [comment]
It's triggered on push and on pull requests

**Comment by oSumAtrIX** [comment]
This means that releases would be created for any commit, including refactoring. A workaround is appending [skip ci] to any commit which should not be released. A fix would be to rely on a specification for commits such as [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/). This would allow for proper integration with [semantic-release](https://github.com/semantic-release/semantic-release).

**Comment by KevinX8** [comment]
> This means that releases would be created for any commit, including refactoring. A workaround is appending [skip ci] to any commit which should not be released. A fix would be to rely on a specification for commits such as [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/). This would allow for proper integration with [semantic-release](https://github.com/semantic-release/semantic-release).

Releases aren't automated, the CI/CD is meant for checking if a commit passes tests and builds. There is no real benefit to having release builds be automated as the windows builds require NSIS and Android builds need to be approved by the playstore.

**Comment by oSumAtrIX** [comment]
It's more about the releases on GitHub. For NSIS a windows machine can be used (if there's no support on Linux).
